// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKoJy5DtTA887m9tfOI1LjfBxnsdb8P9w',
    appId: '1:241323065528:web:55b6ceac2fbcb76f52b44d',
    messagingSenderId: '241323065528',
    projectId: 'wisataapp-59198',
    authDomain: 'wisataapp-59198.firebaseapp.com',
    storageBucket: 'wisataapp-59198.appspot.com',
    measurementId: 'G-2PJM3TQ3NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkjhjT1GeebWJVwJuZRro43PpwmUZpbuM',
    appId: '1:241323065528:android:5e74f6a7ebc7f8bb52b44d',
    messagingSenderId: '241323065528',
    projectId: 'wisataapp-59198',
    storageBucket: 'wisataapp-59198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfvnpAUh4Il55QnIiWSFYiNIf5lga0-_Q',
    appId: '1:241323065528:ios:fce46b28b399fe0852b44d',
    messagingSenderId: '241323065528',
    projectId: 'wisataapp-59198',
    storageBucket: 'wisataapp-59198.appspot.com',
    iosBundleId: 'com.example.loginFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfvnpAUh4Il55QnIiWSFYiNIf5lga0-_Q',
    appId: '1:241323065528:ios:fce46b28b399fe0852b44d',
    messagingSenderId: '241323065528',
    projectId: 'wisataapp-59198',
    storageBucket: 'wisataapp-59198.appspot.com',
    iosBundleId: 'com.example.loginFlutterApp',
  );
}
